import React from 'react';
import { ScrollView, Text, StyleSheet, View } from 'react-native';

export default function TermsScreen() {
  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      <Text style={styles.title}>Terms of Service</Text>
      <Text style={styles.meta}>Last updated: April 2025</Text>

      <Section heading="Single user">
        This app is built for and used by one person only. It is not a public
        service, not available to others, and not intended for any commercial
        purpose.
      </Section>

      <Section heading="No data sharing">
        No data collected or generated by this app is shared with any third
        party, used for advertising, or transmitted to any external server.
      </Section>

      <Section heading="No commercial use">
        This app is strictly for personal, private use. It is not offered as a
        product or service and generates no revenue.
      </Section>

      <Section heading="Data storage">
        All data stays on your device in localStorage. Nothing is persisted
        remotely. You own everything.
      </Section>

      <Section heading="Liability">
        This app is provided as-is for personal convenience. There are no
        warranties, guarantees, or obligations of any kind.
      </Section>
    </ScrollView>
  );
}

function Section({ heading, children }: { heading: string; children: React.ReactNode }) {
  return (
    <View style={styles.section}>
      <Text style={styles.heading}>{heading}</Text>
      <Text style={styles.body}>{children}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0d0d0d',
  },
  content: {
    padding: 28,
    paddingBottom: 60,
  },
  title: {
    fontFamily: 'DMSerifDisplay_400Regular',
    fontSize: 32,
    color: '#f5f0e8',
    marginBottom: 6,
  },
  meta: {
    fontSize: 13,
    color: '#666',
    marginBottom: 36,
    letterSpacing: 0.3,
  },
  section: {
    marginBottom: 28,
  },
  heading: {
    fontFamily: 'DMSerifDisplay_400Regular',
    fontSize: 18,
    color: '#c9b99a',
    marginBottom: 8,
  },
  body: {
    fontSize: 15,
    color: '#a8a8a8',
    lineHeight: 24,
  },
});
